### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by kabus1917** [olekhov/mosauth#1]
Здравствуйте. У вас работает? Похоже опять поломали(((
DEBUG:root:Открываем портал www.mos.ru
DEBUG:root:Начало аутентификационной сессии
ERROR:root:Церемония поменялась
Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    mosau.AuthenticateByESIA(pguconfig)
  File "/root/scripts/mosauth/mosauth/mosauth.py", line 65, in AuthenticateByESIA
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

https://github.com/olekhov/mosauth/blob/25f51db6ce9c25e03d7b85895bab91129e1838fc/mosauth/mosauth.py#L61
Тут 302 вместо 303 выдает, и редирект на https://login.mos.ru/auth/authenticationWS/proxyAe......

**Comment by olekhov** [comment]
Починил.

**Comment by kabus1917** [comment]
Спасибо.
